### ISSUE TITLE
Battery Management/Testing

### ISSUE THREAD

**Issue by josephtcoyle** [FRC-6217/Team2020#14]
Good read…
https://team1640.com/wiki/index.php/Battery_Management

Reference analysis tool…
http://www.westmountainradio.com/product_info.php?products_id=cba4

**Comment by BrightonLochner** [comment]
http://www.ctr-electronics.com/battery-testing/battery-beak.html

**Comment by BrightonLochner** [comment]
https://powerwerx.com/cba-iv-4-computerized-battery-analyzer?gclid=EAIaIQobChMItM-dkqSY5gIVhMBkCh0HzQEfEAYYASABEgJduPD_BwE

**Comment by buchheitriley** [comment]
> http://www.ctr-electronics.com/battery-testing/battery-beak.html

"The Battery Beak does not identify all failed batteries. As a result, reliance on the Battery Beak alone exposes the team to battery failures in competition (as at Westtown & MAR Championships). "
-Quote taken from team 1640 wiki page

**Comment by buchheitriley** [comment]
A new folder was created within the google drive Robotics Drive labelled "Battery".  We tested each battery with the Battery Beak device where one battery was found to be bad. All data was recorded on a google sheets document. Next step is to look at new batteries to purchase. Scouring forums to see what other teams use or what they suggest are good batteries to invest in.

**Comment by josephtcoyle** [comment]
Purchased Battery Tester from PowerWerx
