### ISSUE TITLE
Game Strategy during autonomous

### ISSUE THREAD

**Issue by kristyallen6217** [FRC-6217/Team2020#34]

**Comment by Zoejesh6217** [comment]
Auto program 1                      ***Programs 1&3 might require driving before shooting***
Robot A configuration
- shoot at angle
    - with optional delay
- drive away from line toward trench or rendezvous point
?pick up balls? 

Auto program 2
Robot B configuration
- shoot center, try for inner port
   - optional delay
- drive away (same locations) 
?pick up balls?

Auto program 3
Robot C configuration
- shoot at angle
   - optional delay
-drive away (same locations)
?pick up balls?

**Comment by Zoejesh6217** [comment]
Auto program 4
Robot configuration A or C
- load balls into center robot
- drive off line and potentially pick up balls
